### ISSUE TITLE
At last log plots with exponential fits.

### ISSUE THREAD

**Issue by TakeItAndRun** [valeriupredoi/COVID-19_LINEAR#1]
Thanks for your work.
Lets hope that the media will pick it up and explain it to the world.

**Comment by valeriupredoi** [comment]
much appreciated :beer: Stay safe!

**Comment by valeriupredoi** [comment]
closing this, appreciate the compliment once again, have a look at my site where all this is shown in a nice manner https://valeriupredoi.github.io/ - have a good weekend :beer:
