### ISSUE TITLE
Document the mathematical model behind your projections

### ISSUE THREAD

**Issue by cipriancraciun** [valeriupredoi/COVID-19_LINEAR#11]
It would be nice if you would document the mathematical model in the `readme`, so that others that might want to apply it would be able to use it, without reverse-engineering the formulas.

**Comment by valeriupredoi** [comment]
@cipriancraciun cheers for the issue and suggestion! I have now included a memo [here](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/Mathematical_Model.md) describing what the model is and what parameters are being measured :beer:

**Comment by cipriancraciun** [comment]
(Disclaimer:  my math is so rusty that I don't think it has any metal left in it.)  :)

So, I've read your note a few times, and played with Wolfram Alpha to test my assumptions, and the following are a few observations:
* for most people `exp` and `log` are "esoteric" enough not to grasp their meaning;  instead powers (although still quite "exotic") are perhaps more "understandable";
* therefore when you say that `N(t) = N0 * exp(R*t)` actually that can be rewritten as `N(t) = N0 * 2^(D*t)` where `D = ln(2)/R` or `R = ln(2)/D`;  (`R` is your `b` or `m`, `D` is your `double time` values;)
* the daily `R` would be `R = ln(1+P)` (where `P` is the perceptual increase from the previous day), therefore the daily would be `D = ln(2) / ln(1+P)`;
* (I'm insisting on `D`, the number of days for doubling, because a normal person can "grasp" its meaning, meanwhile `R` is "meaningless" for such a person;)
* my assumption is that `R` and `D` can only be computed for "cumulative" counts, therefore they don't give the usual person a "grasps" when their values are on the "good side";  **is there such a number that is "intuitive" in both its "magnitude" but also "direction"?**
* the "time evolution of rates" does not explain how fits are performed over subsets of datapoints, nor how these datapoints are chosen;  (also the part about `R` dropping below 0.95 is not very clear;)  (it might be only my fault, given how bad my math is;)  :)
* the part about "estimating the actual number of cases" seems pretty readable, however you mention `M` (the estimated mortality rate of the total infected people) but thereafter you don't use it anywhere;  my assumption is that it should be taken into account in `f(m)`?
* my assumption is that this `f(m)` is actually a constant, specific to each country and period;
* also shouldn't the formula be `C(t) = C(t-20) exp(f(m)*20)` (because we actually use `C(t-20)` as the base, so since `t-20` until `t` there are only `20` days, not `t`;  (although I think something is wrong with this formula, see bellow;)
* but still, the section doesn't say how we get from deaths (which we know to be more predictable) to actual confirmed cases;  is it perhaps `C(t) = M * D(t+20)` therefore the actual formula is `C(t) = M * D(t) * exp(f(m)*20)`;

The bottom-line, I think I'll be able to integrate into my dataset for the moment the daily doubling confirmed and death values. (Perhaps with a moving average.)

**Comment by valeriupredoi** [comment]
very good points! I have plugged in your suggestions in the memo (there was a wee mistake in your evolution with doubling times) but cheers, it is indeed a bit more straightforward now :beer: 

> my assumption is that this f(m) is actually a constant, specific to each country and period;

yes indeed, but varies slowly with time, on 7-10-day time scales

> my assumption is that R and D can only be computed for "cumulative" counts, therefore they don't give the usual person a "grasps" when their values are on the "good side"; is there such a number that is "intuitive" in both its "magnitude" but also "direction"?

very good question! I guess doubling times can be looked at and observed as to how they increase/decrease. But I can't think of anything that's quantifiable in terms of direction as well as magnitude...any ideas?

**Comment by cipriancraciun** [comment]
The last formula `C(today) = M x D(today) x exp(f(m) x 20)` I still think is not correct;  shouldn't it actually be `C(today) = M x D(today-20) x exp(f(m) x 20)`?

Regarding another alternative to doubling times that is both quantifiable by average people, and also has a direction, I have no idea...  My best approximation is percentage of change (i.e. `P = N(t)/(t-1)-1`

**Comment by valeriupredoi** [comment]
done, cheers muchly for your input, have a look at my new site https://valeriupredoi.github.io/ :beer:
