### ISSUE TITLE
Adding U.S. State data analysis capabilities

### ISSUE THREAD

**Issue by nsgates** [valeriupredoi/COVID-19_LINEAR#4]
Hi Valeriu, thanks for creating this great resource! I created a branch and modified the code to apply the plotting script to each of the U.S. States, as well as aggregate and compare the statistics. Can you give me access to this repo so I can push my branch and then create a pull request? I'd be happy to add this feature here.

**Comment by valeriupredoi** [comment]
hi @nsgates - brilliant, cheers for the interest, I just added you! Go ahead and open a PR, cheers :beer:

**Comment by nsgates** [comment]
Thanks! I’ll get that taken care of later today.

**Comment by valeriupredoi** [comment]
@nsgates I have now refactored the code and I added the capability to get numbers for US states and other regions that come as the first element in the csv data files, try it with `--regions [list]` or `--regions FILE` just as the other `--countries` option works, can use it together - the command line options are not mutually exculsive :beer:

**Comment by valeriupredoi** [comment]
closing this since US states are correctly implemented via `--regions` :beer:
