### ISSUE TITLE
different number of deaths United Kingdom

### ISSUE THREAD

**Issue by chrisdane** [valeriupredoi/COVID-19_LINEAR#6]
Hi

Today, 2020-03-19, I find 72 deaths in United Kingdom reported for yesterday, 2020-03-18, derived from both the `csse_covid_19_time_series` as well as the `csse_covid_19_daily_reports` files (commit 6012c62 of the upstream). https://hgis.uw.edu/virus/ reports 71 for that date (2020-03-18).

On your first plot, however, it looks like you have something between 114 and 144 deaths in United Kingdom. Did I miss some entries? Which rows do you sum for "United Kingdom"? I sum all rows whose "Country/Region"-column entry equals "United Kingdom": see https://github.com/chrisdane/COVID-19/tree/mybranch/r_plots (search for United Kingdom).

Also, isn't the reported "Death" number in the data rather cumulative than "daily", as your plots indicate? I am confused about this ...

Btw, thanks for the inspiration and stay healthy =)
Chris

**Comment by valeriupredoi** [comment]
Hi @chrisdane - for the UK I am not using the Johns Hopkins data but rather the government one [here](https://www.gov.uk/government/publications/covid-19-track-coronavirus-cases) that is in the Daily Indicators. The problem with that data is that is shown every day but also removed every day and replaced with the new data from the next day; I don't know why they do that. here's the [log](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_data/UK_deaths_history)

The JH data says:
```
United Kingdom,2020-03-18T14:53:05,2626,71,65 (wrong)
United Kingdom,2020-03-17T15:13:09,1950,55,52 (wrong)
United Kingdom,2020-03-16T19:13:13,1543,55,20 (correct)
United Kingdom,2020-03-14T14:53:04,1140,21,18 -> supposed to be 15-03
United Kingdom,2020-03-14T14:53:04,1140,21,18 (correct)
United Kingdom,2020-03-11T20:00:00,798,8,18 -> supposed to be 13-03
```

So yeah the JH data is wonky for the UK - I suspect they are having issues with the retrieval since the UK is not really that open and systematic in logging the deaths' data
 :beer:

**Comment by valeriupredoi** [comment]
> Btw, thanks for the inspiration and stay healthy =)

Cheers muchly, you too!

**Comment by valeriupredoi** [comment]
> Also, isn't the reported "Death" number in the data rather cumulative than "daily", as your plots indicate? I am confused about this

indeed, but my plots are all cumulative (says on the y-axis :grin: )

**Comment by valeriupredoi** [comment]
in [your plot](https://github.com/chrisdane/COVID-19/blob/mybranch/r_plots/plots/United_Kingdom/United_Kingdom_cumulative_deaths_logy.png) you need to shift by a couple days the data and plug in the data from my log, could you you pls send me a link to that? I am very worried about our rather high death rate so far. Cheers mate :beer:

**Comment by chrisdane** [comment]
dont understand what you mean :/ link to what? what log?

**Comment by valeriupredoi** [comment]
this log: https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_data/UK_deaths_history (that was a link :) )

**Comment by chrisdane** [comment]
Ah I see ^^

Now another question: on your Germany plot, the linear model coefficient for cumulative deaths is 0.33 (I guess in units `days^-1`; the unit is not given). I get the same result. From this you infer that the doubling time is 2.1 days. How? (0.33 days^-1)^-1 is ~3 days.

**Comment by valeriupredoi** [comment]
you are missing an `ln(2)` factor:
```
N = N0 exp(bt)
2N0 = N0 exp(b x doub_t)
b x doub_t = ln(2)
doub_t = ln(2) / b
```

**Comment by chrisdane** [comment]
Ah, thank you. At the time point of doubling numbers, `doub_t`, `N \stackrel{!}{=} 2N0`. Then, your lines apply. Omg, I tried to derive exponential regression for hours without success =( Totally overthinking the problem...

**Comment by valeriupredoi** [comment]
not a problem, scary data, have never worked with such scary data before. You can just do a continuation of the current exponential curve linearlized in log space - like I do for the [UK here](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_plots/COVID-19_LIN_UK_DARK_SIM_UK.png) - keep the current rates and add a best scenario quarantine works rate like 0.15 or 0.20. Cheers, do you mind if I close the issue now? :beer:

**Comment by chrisdane** [comment]
Sure, thanks!

On March 22, 2020 2:53:50 PM GMT+01:00, Valeriu Predoi <notifications@github.com> wrote:
>not a problem, scary data, have never worked with such scary data
>before. You can just do a continuation of the current exponential curve
>linearlized in log space - like I do for the [UK
>here](https://github.com/valeriupredoi/COVID-19_LINEAR/blob/master/country_plots/COVID-19_LIN_UK_DARK_SIM_UK.png)
>- keep the current rates and add a best scenario quarantine works rate
>like 0.15 or 0.20. Cheers, do you mind if I close the issue now? :beer:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/valeriupredoi/COVID-19_LINEAR/issues/6#issuecomment-602204165

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
